# Demo configuração para rodar local no docker
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
        - 'localhost:9090'

  - job_name: api
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
    - targets: 
        - 'api:80'
      labels:
        team: api

  - job_name: mongodb_exporter
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
    - targets: 
      - 'mongo-exporter:9216'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets: 
          - 'alertmanager:9093'